StartupEvents.registry('block', event => {
	event.create('pebble_block')
	.displayName('Pebble')
	.soundType('stone')
	.mapColor('stone')
	.defaultCutout()
	.opaque(true)
	.fullBlock(false)
	.box(9, 0, 8, 6, 1, 6, true)
	.requiresTool(false)
	.tagBlock('minecraft:mineable/pickaxe')
	.hardness(0.25)
	.resistance(1.0)

	event.create('dry_dirt')
	.displayName('Dry Dirt')
	.soundType('stone')
	.mapColor('stone')
	.opaque(true)
	.fullBlock(true)
	.requiresTool(true)
	.tagBlock('minecraft:mineable/pickaxe')
	.hardness(0.5)
	.resistance(2.0)
})