
[general]
	#The material blacklist of this module.
	materialBlacklist = ["lithium", "molybdenum", "titanium", "vanadium"]
	#The materials to force generate passive forms for this module.
	passiveMaterialWhitelist = []

