
[general]
	#The material blacklist of this module.
	materialBlacklist = ["ash", "brick", "endereye", "fissile", "glowstone", "lithium", "mercury", "molybdenum", "nether_brick", "obsidian", "prismarine", "saltpeter", "silica", "slag", "sulfur", "superconductive", "thorium", "vanadium"]

